 let data = {
  deals: [
    {
      Layout_id: "6736950000000593588",
      Deal_Name: "Diamond Earrings Set",
      Stage: "Closed Won",
      Pipeline: "ARG",
      Amount: 45000,
      Closing_Date: "2025-10-15",
      Account_Name: "Elite Diamonds",
      Account_Id: "6946766000000591172",
      Contact_Name: "Fatima Ali",
      Contact_Id: "6946766000000877164",
      Email: "fatima@elitediamonds.com",
      Phone: "0503456789",
      Description: "Premium diamond earrings with matching set",
      Customer_interest: "Diamond",
      Initial_Interest: "Earrings",
      Category: "Earrings",
      Sub_Category: "Diamond Earrings",
      Brand: "Luxury",
      Style: "Modern",
      Size: "Standard",
      Design: "DE-004",
      Prefix_Code: "DIAM",
      Main_Stock_Code: "DE-2025-004",
      Stock_Code: "DE004",
      Price_Code: "PC-DIAM-2",
      Purity: "18K",
      Metal_Colour: "Platinum",
      Gross_Weight: "12.5",
      Net_Weight: "11.8",
      Stone_Weight: "1.5",
      Stone_Rate: "20000",
      PCS: "1",
      Making: "4000",
      Making_Price_1: "3500",
      Making_Price_2: "4000",
      Making_Price_3: "4500",
      Wastage: "2%",
      Supplier_Name: "Premium Stones LLC",
      Supplier_Purchase_Number: "SUP-2025-004"
    }
  ],
  apply_feature_execution: [{ name: "layout_rules" }],
  skip_feature_execution: [{ name: "cadences" }],
  trigger: ["approval", "workflow", "blueprint", "pathfinder", "orchestration"]
};

let transaction = {
  data: [
    {
      Layout_id: "6946766000000992011",
      // Name: "Test Gold", // Zoho expects field API name 'Name' for record name
      id: "6946766000000996082",
      Owner: { id: "6946766000000572001", email: "accounts@arggoldanddiamonds.com", name: "ARG GOLD AND DIAMONDS TRADING L.L.C" },
      Created_By: { name: "ARG GOLD AND DIAMONDS TRADING L.L.C" },
      Created_Time: "2025-11-04T16:13:58+04:00",
      Modified_By: { name: "ARG GOLD AND DIAMONDS TRADING L.L.C" },
      Modified_Time: "2025-11-07T09:34:29+04:00",
      $approval_state: "approved",
      Customer_interest: "Gold",
      Prefix_Code: "teste12",
      Stone_Weight: "test",
      Making: "testr4537",
      Making_Price_1: null,
      Making_Price_2: "testub12",
      Making_Price_3: null,
      Category: null,
      Sub_Category: null,
      Style: null,
      Design: null,
      Brand: null,
      Purity: null,
      Metal_Colour: null,
      Metal_Carat: null,
      Metal_Rate_pure: null,
      Metal_Value: null,
      Metal_WT: null,
      Gross_Weight: null,
      Net_Weight: null,
      Stone_Rate: null,
      Stone_Value: null,
      Stone_Selling_Rate_Per_Carat: null,
      Stone_Selling_Value: null,
      Diamond_Selling_Rate: null,
      Diamond_Selling_Value: null,
      Diamond_Amount_Per_CT: null,
      DIA_Carat_Weight: null,
      Diamond_Size: null,
      Diamond_Clarity: null,
      No_of_Diamonds: null,
      Wastage: null,
      Labour_Charges: null,
      Polishing_Charges: null,
      Setting_Charges: null,
      Misc_Charges: null,
      Rhodium_Charges: null,
      Cost: null,
      Cost_Code: null,
      Price_Code: null,
      Tag_Price_1: null,
      Tag_Price_2: null,
      Tag_Price_3: null,
      Tag_line_1: null,
      Tag_line_2: null,
      Tag_line_3: null,
      Tag_line_4: null,
      Tag_line_5: null,
      Supplier_Name: null,
      Supplier_Purchase_Number: null,
      Supplier_Ref: null,
      Stock_Code: null,
      Main_Stock_Code: null,
      Metal_Division: null,
      Item_Division: null,
      Diamond_Division: null,
      Type: null,
      Quantity: null,
      PCS: null,
      Design_Number: null,
      Certificate_Number: null,
      Country: null,
      Description: null,
      Deals: { id: "6946766000000785168", name: "Sandra Speering" },
      $currency_symbol: "$",
      Locked__s: false,
      $editable: true
    }
  ],
  apply_feature_execution: [{ name: "layout_rules" }],
  skip_feature_execution: [{ name: "cadences" }],
  trigger: ["approval", "workflow", "blueprint", "pathfinder", "orchestration"]
};


module.exports = { data, transaction };